### ISSUE TITLE
The camlp5 situation

### ISSUE THREAD

**Issue by Simn** [ocaml-opam/opam-repository-mingw#14]
Camlp5 used to have custom patches in the fdopen repo to make it work on Windows, see here: https://github.com/camlp5/camlp5/issues/77#issuecomment-782529159

The last version that I found which has this patch is `camlp5.8.00.03`. Since it's been almost 3 years and this hasn't been fixed in camlp5 itself yet, would it be possible to bring back the patch for more recent versions? I'm trying to find an upgrade path to OCaml 5 and this is one of the blockers.

**Comment by dra27** [comment]
I'm afraid this either needs to be fixed upstream or you'll need to fork the repository and migrate the patches yourself to a more recent version (assuming it works). I'm afraid it's beyond the scope of what this repository's being used for (see https://github.com/ocaml-opam/opam-repository-mingw?tab=readme-ov-file#updates).
