### ISSUE TITLE
Opam can't use this reporsitory with opam-2.2.0~beta1 on Windows

### ISSUE THREAD

**Issue by F-Loyer** [ocaml-opam/opam-repository-mingw#15]
When trying a `opam init https://github.com/ocaml-opam/opam-repository-mingw`, I have the following error:

```
<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><>  🐫
[ERROR] Could not update repository "default": OpamDownload.Download_fail(_, "curl: code 404 while downloading
        https://github.com/ocaml-opam/opam-repository-mingw/index.tar.gz")
[ERROR] Initial download of repository failed.
```

I am using opam-2.2.0~beta1 on Windows.

**Comment by kit-ty-kate** [comment]
This is not an issue related to this repository, only a typo, see: https://github.com/ocaml/opam/issues/5798#issuecomment-1906357143
