### ISSUE TITLE
Fail to build ocamlbuild

### ISSUE THREAD

**Issue by F-Loyer** [ocaml-opam/opam-repository-mingw#16]
I have the following error:

```
$ opam install ocamlbuild
The following actions will be performed:
=== install 1 package
  ∗ ocamlbuild 0.14.2

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫


#=== ERROR while fetching sources for ocamlbuild.0.14.2 =======================#
OpamSolution.Fetch_fail("C:\\Cygwin\\usr\\local\\bin\\opam.exe: \"lstat\" failed on C:\\Cygwin\\tmp\\opam-14672-316ab8\\ocamlbuild-0.14.2\\examples\\07-dependent-projects\\libdemo: No such file or directory")


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫

┌─ The following actions failed
│ ⬇ fetch ocamlbuild 0.14.2
└─
╶─ No changes have been performed

```

However, curiously, `C:\\Cygwin\\tmp\\opam-14672-316ab8\\ocamlbuild-0.14.2\\examples\\07-dependent-projects\\libdemo` does exist.

I am using the `ocaml-variants.4.14.1+mingw64c` variant from opam-2.2.0~beta1.

**Comment by F-Loyer** [comment]
I have fixed the compilation... Cygwin needs a `CYGWIN=winsymlinks:nativestrict` environment.

This works only if the user has enough privileges. One have to get `gpedit.msc` / Computer Settings / Windows parameters / security settings / Local strategies / Users rights / Create symlinks.

**Comment by F-Loyer** [comment]
I have fixed the compilation... Cygwin needs a CYGWIN=winsymlinks:nativestrict environment.

This works only if the user has enough privileges. One have to get gpedit.msc / Computer Settings / Windows parameters / security settings / Local strategies / Users rights / Create symlinks.

I guess a documentation upgrade is needed, but it doesn't deal with opam-repository-mingw

**Comment by dra27** [comment]
As in #17, this was mitigated by https://github.com/ocaml/opam/pull/5953 in 2.2.0~beta3, so should be fine now (albeit with a warning when the tarball is extracted).
