### ISSUE TITLE
Fail to compile ocp-indent on Windows

### ISSUE THREAD

**Issue by F-Loyer** [ocaml-opam/opam-repository-mingw#17]
On Windows (opam.2.20~beta1, mingw, CYGMWIN set to `winsymlinks:nativestrict`), ocp-indent doesn't build.

The tar file contains:
```
lrwxrwxrwx root/root         0 2019-10-21 12:03 ocp-indent-1.8.1/tests/inplace/link.ml -> otherfile.ml
lrwxrwxrwx root/root         0 2019-10-21 12:03 ocp-indent-1.8.1/tests/inplace/link2.ml -> link.ml
-rw-rw-r-- root/root         0 2019-10-21 12:03 ocp-indent-1.8.1/tests/inplace/otherfile.ml
```
And Windows doesn't like to create a symlink to a file which doesn't exist yet. (Here link.ml should point to otherfile.ml, but it will be created afterwards).

I can't even `opam source ocp-indent`.

**Comment by dra27** [comment]
This was mitigated by https://github.com/ocaml/opam/pull/5953 in 2.2.0~beta3, so should be fine now (albeit with a warning when the tarball is extracted).
