### ISSUE TITLE
How to install opam itself

### ISSUE THREAD

**Issue by MSoegtropIMC** [ocaml-opam/opam-repository-mingw#6]
Thanks for the initiative!

One thing which is unclear from the description, though is how to install opam itself. The fdopen repo had releases with patched binary opam versions, say https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz. Should I continue to use these?

**Comment by dra27** [comment]
Sorry for the slow reply - yes, indeed, this repo is intended to be used with those old installers. This repo should also be usable with opam 2.2 (but it won't be added by default, as the upstream release of opam will of course use upstream ocaml/opam-repository by default, as on other platforms).

**Comment by MSoegtropIMC** [comment]
Thanks!

I wonder how I should compile Opam 2.2. I guess one still needs the Cygwin / MinGW cross method (many opam packages need a posix shell to build) and as far as I know many of the patches done by fdopen are around supporting this. Does Opam 2.2 support cross build environments?

**Comment by dra27** [comment]
It took a while, but with opam 2.2.0 finally released, I think this is dealt with: opam is available (unpatched) in winget, and there are also full instructions at https://github.com/ocaml/opam?tab=readme-ov-file#compiling-on-native-windows for building it "from cold" (Cygwin is indeed required, either with its mingw-w64 cross-compilers or with Visual Studio)
